repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        types_or: [css, javascript]
        additional_depdencies:
            - prettier@2.8.4
