# Generated by Django 4.2.1 on 2023-05-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechmodel',
            name='segments',
            field=models.JSONField(null=True),
        ),
    ]
